<h1> Operçõpes Móveis (Média, Soma, Máx e Min) </h1>
<br>
<i>
• Importar biblioteca pandas <br>
• Importar um arquivo Excel<br>
• Média Móvel de 5 em 5 linhas <br>
• Média Móvel de 5 em 5 linhas, com período mínimo = 1 <br>    
• Soma móvel de 3 em 3<br>
• Maior móvel de 3 em 3<br>
• Menor móvel de 3 em 3<br>

In [8]:
import pandas as pd
dataset1 = pd.read_excel('covid.xlsx', sheet_name='Baixada_Santista')
dataset2 = pd.read_excel('covid.xlsx', sheet_name='Mensal_baixada_santista')

display(dataset1)
display(dataset2.head(2))

         CIDADE               Bairro  Mortes Covid
0       Guaruja        Santo Antônio             7
1       Guaruja           Santa Rosa             4
2       Guaruja              Enseada             2
3       Guaruja            Morrinhos             5
4       Guaruja  Vicente de Carvalho            10
5        Santos               Macuco             9
6        Santos          Radio Clube             8
7        Santos          José Menino             5
8        Santos              Valongo             4
9        Santos               Embaré             1
10  São Vicente               Centro            10
11  São Vicente             Catiapoa             5
12  São Vicente       Cidade Náutica             2

         Mês  Morte
0    Janeiro      2
1  Fevereiro      2

<h3> Média Móvel de 5 em 5 linhas </h3>

In [9]:
dataset1['Média Movel 5'] = dataset1.rolling(window=5).mean()
#dataset1['teste'] = dataset1['Mortes Covid'].rolling(window=5).mean
display(dataset1)

         CIDADE               Bairro  Mortes Covid  Média Movel 5
0       Guaruja        Santo Antônio             7            NaN
1       Guaruja           Santa Rosa             4            NaN
2       Guaruja              Enseada             2            NaN
3       Guaruja            Morrinhos             5            NaN
4       Guaruja  Vicente de Carvalho            10            5.6
5        Santos               Macuco             9            6.0
6        Santos          Radio Clube             8            6.8
7        Santos          José Menino             5            7.4
8        Santos              Valongo             4            7.2
9        Santos               Embaré             1            5.4
10  São Vicente               Centro            10            5.6
11  São Vicente             Catiapoa             5            5.0
12  São Vicente       Cidade Náutica             2            4.4

<h3> Média Móvel de 5 em 5 linhas, com período mínimo = 1 </h3>
<br>
As primeiras linhas não teria média, mas com período mínimo 1, ele faz com a quantidade de valores que tem.

In [10]:
dataset1['Média Móvel5 * '] = dataset1['Mortes Covid'].rolling(window=5, min_periods=1).mean()
display(round(dataset1,1))

,CIDADE,Bairro,Mortes Covid,Média Movel 5,Média Móvel5 *
0,Guaruja,Santo Antônio,7,NaN,7.0
1,Guaruja,Santa Rosa,4,NaN,5.5
2,Guaruja,Enseada,2,NaN,4.3
3,Guaruja,Morrinhos,5,NaN,4.5
4,Guaruja,Vicente de Carvalho,10,5.6,5.6
5,Santos,Macuco,9,6.0,6.0
6,Santos,Radio Clube,8,6.8,6.8
7,Santos,José Menino,5,7.4,7.4
8,Santos,Valongo,4,7.2,7.2
9,Santos,Embaré,1,5.4,5.4
10,São Vicente,Centro,10,5.6,5.6
11,São Vicente,Catiapoa,5,5.0,5.0
12,São Vicente,Cidade Náutica,2,4.4,4.4

In [11]:
dataset1['Média Móvel5 - center '] = dataset1['Mortes Covid'].rolling(window=5,  center=True).mean()
display(round(dataset1,1))

,CIDADE,Bairro,Mortes Covid,Média Movel 5,Média Móvel5 *,Média Móvel5 - center
0,Guaruja,Santo Antônio,7,NaN,7.0,NaN
1,Guaruja,Santa Rosa,4,NaN,5.5,NaN
2,Guaruja,Enseada,2,NaN,4.3,5.6
3,Guaruja,Morrinhos,5,NaN,4.5,6.0
4,Guaruja,Vicente de Carvalho,10,5.6,5.6,6.8
5,Santos,Macuco,9,6.0,6.0,7.4
6,Santos,Radio Clube,8,6.8,6.8,7.2
7,Santos,José Menino,5,7.4,7.4,5.4
8,Santos,Valongo,4,7.2,7.2,5.6
9,Santos,Embaré,1,5.4,5.4,5.0
10,São Vicente,Centro,10,5.6,5.6,4.4
11,São Vicente,Catiapoa,5,5.0,5.0,NaN
12,São Vicente,Cidade Náutica,2,4.4,4.4,NaN

<h3>Soma móvel de 3 em 3 </h3>

In [12]:
dataset1['Soma Móvel  3x3'] = dataset1['Mortes Covid'].rolling(window=3, min_periods=1).sum()
display(dataset1)

,CIDADE,Bairro,Mortes Covid,Média Movel 5,Média Móvel5 *,Média Móvel5 - center,Soma Móvel 3x3
0,Guaruja,Santo Antônio,7,NaN,7.000000,NaN,7.0
1,Guaruja,Santa Rosa,4,NaN,5.500000,NaN,11.0
2,Guaruja,Enseada,2,NaN,4.333333,5.6,13.0
3,Guaruja,Morrinhos,5,NaN,4.500000,6.0,11.0
4,Guaruja,Vicente de Carvalho,10,5.6,5.600000,6.8,17.0
5,Santos,Macuco,9,6.0,6.000000,7.4,24.0
6,Santos,Radio Clube,8,6.8,6.800000,7.2,27.0
7,Santos,José Menino,5,7.4,7.400000,5.4,22.0
8,Santos,Valongo,4,7.2,7.200000,5.6,17.0
9,Santos,Embaré,1,5.4,5.400000,5.0,10.0
10,São Vicente,Centro,10,5.6,5.600000,4.4,15.0
11,São Vicente,Catiapoa,5,5.0,5.000000,NaN,16.0
12,São Vicente,Cidade Náutica,2,4.4,4.400000,NaN,17.0

<h3> Maior móvel de 3 em 3 </h3>

In [14]:
dataset1['Maior Móvel  3x3'] = dataset1['Mortes Covid'].rolling(window=3, min_periods=1).max()
display(dataset1)

,CIDADE,Bairro,Mortes Covid,Média Movel 5,Média Móvel5 *,Média Móvel5 - center,Soma Móvel 3x3,Maior Móvel 3x3
0,Guaruja,Santo Antônio,7,NaN,7.000000,NaN,7.0,7.0
1,Guaruja,Santa Rosa,4,NaN,5.500000,NaN,11.0,7.0
2,Guaruja,Enseada,2,NaN,4.333333,5.6,13.0,7.0
3,Guaruja,Morrinhos,5,NaN,4.500000,6.0,11.0,5.0
4,Guaruja,Vicente de Carvalho,10,5.6,5.600000,6.8,17.0,10.0
5,Santos,Macuco,9,6.0,6.000000,7.4,24.0,10.0
6,Santos,Radio Clube,8,6.8,6.800000,7.2,27.0,10.0
7,Santos,José Menino,5,7.4,7.400000,5.4,22.0,9.0
8,Santos,Valongo,4,7.2,7.200000,5.6,17.0,8.0
9,Santos,Embaré,1,5.4,5.400000,5.0,10.0,5.0
10,São Vicente,Centro,10,5.6,5.600000,4.4,15.0,10.0
11,São Vicente,Catiapoa,5,5.0,5.000000,NaN,16.0,10.0
12,São Vicente,Cidade Náutica,2,4.4,4.400000,NaN,17.0,10.0

<h3>Menor móvel de 3 em 3 </h3>

In [17]:
dataset1['Menor Móvel  3x3'] = dataset1['Mortes Covid'].rolling(window=3, min_periods=1).min()
display(dataset1)

,CIDADE,Bairro,Mortes Covid,Média Movel 5,Média Móvel5 *,Média Móvel5 - center,Soma Móvel 3x3,Maior Móvel 3x3,Menor Móvel 3x3
0,Guaruja,Santo Antônio,7,NaN,7.000000,NaN,7.0,7.0,7.0
1,Guaruja,Santa Rosa,4,NaN,5.500000,NaN,11.0,7.0,4.0
2,Guaruja,Enseada,2,NaN,4.333333,5.6,13.0,7.0,2.0
3,Guaruja,Morrinhos,5,NaN,4.500000,6.0,11.0,5.0,2.0
4,Guaruja,Vicente de Carvalho,10,5.6,5.600000,6.8,17.0,10.0,2.0
5,Santos,Macuco,9,6.0,6.000000,7.4,24.0,10.0,5.0
6,Santos,Radio Clube,8,6.8,6.800000,7.2,27.0,10.0,8.0
7,Santos,José Menino,5,7.4,7.400000,5.4,22.0,9.0,5.0
8,Santos,Valongo,4,7.2,7.200000,5.6,17.0,8.0,4.0
9,Santos,Embaré,1,5.4,5.400000,5.0,10.0,5.0,1.0
10,São Vicente,Centro,10,5.6,5.600000,4.4,15.0,10.0,1.0
11,São Vicente,Catiapoa,5,5.0,5.000000,NaN,16.0,10.0,1.0
12,São Vicente,Cidade Náutica,2,4.4,4.400000,NaN,17.0,10.0,2.0